;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        backward-sexp
        c-electric-brace
        c-electric-colon
        c-electric-lt-gt
        c-electric-paren
        c-electric-pound
        c-electric-semi&comma
        c-electric-slash
        c-electric-star
        c-indent-line-or-region
        doom/backward-to-bol-or-indent
        doom/forward-to-last-non-comment-or-eol
        drag-stuff-right
        forward-sexp
        ignore
        kill-region
        lsp-ui-doc--handle-mouse-movement
        magit-section-toggle
        my-org-yank
        org-beginning-of-line
        org-cycle
        org-end-of-line
        org-force-self-insert
        org-kill-line
        org-self-insert-command
        scroll-right
        wdired--self-insert
        ))

(setq mc/cmds-to-run-once
      '(
        beginning-of-buffer
        consult-line
        find-build-script-and-compile
        indent-for-tab-command
        mark-word-or-next-word-like-this
        org-export-dispatch
        shell-command
        ))
