;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        backward-sexp
        c-electric-brace
        c-electric-colon
        c-electric-lt-gt
        c-electric-paren
        c-electric-pound
        c-electric-semi&comma
        c-electric-slash
        c-electric-star
        c-indent-line-or-region
        doom/backward-to-bol-or-indent
        doom/forward-to-last-non-comment-or-eol
        drag-stuff-down
        drag-stuff-right
        drag-stuff-up
        forward-sexp
        ignore
        kill-region
        kill-visual-line
        lsp-ui-doc--handle-mouse-movement
        magit-section-toggle
        markdown-outdent-or-delete
        my-org-yank
        org-beginning-of-line
        org-cycle
        org-end-of-line
        org-force-self-insert
        org-kill-line
        org-return
        org-self-insert-command
        org-shiftleft
        org-shiftright
        python-indent-shift-right
        scroll-right
        wdired--self-insert
        xenops-math-insert-closing-paren
        ))

(setq mc/cmds-to-run-once
      '(
        beginning-of-buffer
        consult-buffer
        consult-goto-line
        consult-line
        dired-next-line
        dired-previous-line
        duplicate-line
        find-build-script-and-compile
        find-file
        indent-for-tab-command
        kmacro-end-or-call-macro
        lookup-docs-for-symbol-at-point
        mark-word-or-next-word-like-this
        mc--insert-letter-and-increase
        mc--insert-number-and-increase
        mc/vertical-align-with-space
        mouse-set-region
        org-export-dispatch
        org-roam-node-find
        python-indent-shift-left
        shell-command
        wdired-finish-edit
        ))
